---

- name: get dhall binaries
  unarchive:
    src: "{{ item }}"
    dest: "{{ home }}/bin/"
    remote_src: yes
    extra_opts:
      - --strip=2
      - --wildcards
      - '*/*dhall*'
  loop:
    - https://github.com/dhall-lang/dhall-haskell/releases/download/1.32.0/dhall-1.32.0-x86_64-linux.tar.bz2
    - https://github.com/dhall-lang/dhall-haskell/releases/download/1.32.0/dhall-json-1.6.4-x86_64-linux.tar.bz2
    - https://github.com/dhall-lang/dhall-haskell/releases/download/1.32.0/dhall-yaml-1.1.0-x86_64-linux.tar.bz2
    - https://github.com/dhall-lang/dhall-haskell/releases/download/1.32.0/dhall-lsp-server-1.0.7-x86_64-linux.tar.bz2

...
