---

- name: get dhall binaries
  unarchive:
    src: "{{ item }}"
    dest: "{{ home }}/bin/"
    remote_src: yes
    extra_opts:
      - --strip=2
      - --wildcards
      - '*/*dhall*'
  loop:
    - https://github.com/dhall-lang/dhall-haskell/releases/download/1.31.1/dhall-1.31.1-x86_64-linux.tar.bz2
    - https://github.com/dhall-lang/dhall-haskell/releases/download/1.31.1/dhall-json-1.6.3-x86_64-linux.tar.bz2
    - https://github.com/dhall-lang/dhall-haskell/releases/download/1.31.1/dhall-yaml-1.0.3-x86_64-linux.tar.bz2
    - https://github.com/dhall-lang/dhall-haskell/releases/download/1.31.1/dhall-lsp-server-1.0.6-x86_64-linux.tar.bz2

...
