---

- set_fact:
    dhall_version: "1.35.0"

- name: get releases
  uri:
    url: "https://api.github.com/repos/dhall-lang/dhall-haskell/releases/tags/{{ dhall_version }}"
    return_content: yes
  register: dhall_releases

- name: filter urls
  set_fact:
    dhall_urls: '{{ dhall_releases.json.assets
                    | selectattr("name", "match", regex)
                    | map(attribute="browser_download_url")
                 }}'
  vars:
    regex: "dhall(|-json|-yaml|-lsp-server)-[.0-9]+-x86_64-linux.tar.bz2"

- name: get dhall binaries
  unarchive:
    src: "{{ item }}"
    dest: "{{ home }}/bin/"
    remote_src: yes
    extra_opts:
      - --strip=2
      - --wildcards
      - '*/*dhall*'
  loop: "{{ dhall_urls }}"

...
