---

- name: set aliases
  shell: |
    git config --global alias.co checkout
    git config --global url.git@github.com:emqx/.insteadOf https://github.com/emqx/
    git config --global user.name "{{ git_user_name }}"
    git config --global user.email "{{ git_email }}"
    git config --global init.defaultBranch main
    # https://git-scm.com/book/en/v2/Git-Tools-Rerere
    git config --global rerere.enabled true

...
