---

- name: install packages
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  loop:
    - virt-manager
    - libvirt
    - dnsmasq
    - qemu-desktop
    - edk2-ovmf

- name: setup user groups
  become: yes
  become_user: root
  user:
    name: "{{ my_user }}"
    groups: libvirt
    append: yes

- name: config libvirtd.conf unix_sock_group
  become: yes
  become_user: root
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_group'
    line: 'unix_sock_group = "libvirt"'

- name: config libvirtd.conf unix_sock_rw_perms
  become: yes
  become_user: root
  lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_rw_perms'
    line: 'unix_sock_rw_perms = "0770"'

- name: config qemu.conf user
  become: yes
  become_user: root
  lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '^#user ='
    line: 'user = "{{ my_user }}"'

- name: config qemu.conf group
  become: yes
  become_user: root
  lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '^#group ='
    line: 'group = "{{ my_user }}"'

...
