---

- name: install packages
  become: yes
  become_user: root
  package:
    name:
      - texlive-bin
      - texlive-core
      - texlive-latexextra
      - texlive-science
      - texlive-xetex
    state: present

...
