---

- name: "Config my PC"
  hosts: my-pcs
  connection: local

  vars:
    my_user: "thales"
    home: "{{ ansible_env.HOME }}"

  remote_user: "{{ my_user }}"
  become: yes
  become_user: "{{ my_user }}"

  tasks:
    - name: setup user groups
      user:
        name: "{{ my_user }}"
        groups: root,sys,log,power,adm,wheel,disk,lp,storage,uucp,users,dbus,input
        append: yes
      tags: [user_setup]

  roles:
    - role: aura
      tags: [aura_install]
    - role: packages
      tags: [packages]
    - role: gnupg
      tags: [gnupg]
    - role: zsh
      tags: [zsh]
    - role: asdf
      tags: [asdf]
    - role: devel
      tags: [devel]
    - role: haskell
      tags: [haskell]
    - role: docker
      tags: [docker]
    - role: stumpwm
      tags: [stumpwm]
    - role: xmonad
      tags: [xmonad]
    - role: cl-scripts
      tags: [cl-scripts]

...
