---

- name: "Config my PC"
  hosts: my-pcs
  connection: local

  vars:
    my_user: "thales"
    home: "{{ ansible_env.HOME }}"

  remote_user: "{{ my_user }}"
  become: yes
  become_user: "{{ my_user }}"

  tasks:
    - name: setup user groups
      user:
        name: "{{ my_user }}"
        groups: root,sys,log,power,adm,wheel,disk,lp,storage,uucp,users,dbus
        append: yes
      tags: [user_setup]

  roles:
    - role: packages
    - role: gnupg
      tags: [gnupg]
    - role: zsh
      tags: [zsh]
    - role: asdf
      tags: [asdf]
    - role: haskell
    - role: docker
