---

- name: "Config my PC"
  hosts: my-pcs
  connection: local
  remote_user: "{{ my_user }}"
  become: yes
  become_user: "{{ my_user }}"
  vars:
    my_user: "thales"
  roles:
    - packages
    - zsh
    - haskell
