---

- name: "Config my PC"
  hosts: my-pcs
  connection: local
  remote_user: "{{ my_user }}"
  become: yes
  become_user: "{{ my_user }}"
  vars:
    my_user: "thales"
  roles:
    - role: packages
    - role: zsh
      tags: [zsh]
    - role: asdf
      tags: [asdf]
    - role: haskell
    - role: docker
