---

- name: install packages
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - bind-tools
    - curl
    - emacs
    - figlet
    - git
    - gnupg
    - inotify-tools
    - keynav
    - mtr
    - netcat-openbsd
    - npm
    - pass
    - python-pip
    - silversearcher-ag
    - socat
    - ssh
    - terminator
    - tree
    - vim
    - wget
    - whois
    - xclip
