---

- name: "set up required repositories"
  apt_repository:
    repo: "{{ item }}"
    state: "present"
    update_cache: "yes"
    mode: "644"
  when: False
  with_items:
    - ppa:ansible/ansible
    - ppa:graphics-drivers/ppa

- name: "Install packages"
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    update_cache: "yes"
    cache_valid_time: "3600"
    state: "latest"
  with_items:
    - ansible
    - apt-file
    - build-essential
    - curl
    - dnsutils
    - figlet
    - git
    - inotify-tools
    # - keynav
    - mtr-tiny
    - nodejs
    - npm
    - pass
    - python3-pip
    - silversearcher-ag
    - ssh
    - terminator
    - tmux
    - tree
    - vim
    - wget
    - xclip

- name: Add an alias for Nodejs
  become: yes
  become_user: root
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
