---

- name: install packages
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  loop:
    - acpid
    - ansible
    - bind-tools
    - curl
    - dmenu
    - emacs
    - expect
    - figlet
    - git
    - gnupg
    - idris
    - inotify-tools
    - keynav
    - mtr
    - npm
    - ntp
    - openbsd-netcat
    - pass
    - python-pip
    - ripgrep
    - rofi
    - rustup
    - socat
    - openssh
    - terminator
    - the_silver_searcher
    - tree
    - vim
    - vlc
    - wget
    - whois
    - xclip
    - xorg
    - xorg-drivers
    - xscreensaver

- import_tasks: vlc.yml
  tags: [vlc]

- import_tasks: acpid.yml
  tags: [acpid]

...
