---

- name: install packages
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  loop:
    - acpid
    - ansible
    - bind-tools
    - curl
    - dmenu
    - emacs
    - expect
    - figlet
    - git
    - gnupg
    - idris
    - inotify-tools
    - keynav
    - mtr
    - npm
    - openbsd-netcat
    - pass
    - python-pip
    - ripgrep
    - rofi
    - rustup
    - socat
    - ssh
    - terminator
    - the_silver_searcher
    - tree
    - vim
    - wget
    - whois
    - xclip

...
