---

- name: install basic packages
  become: yes
  become_user: root
  tags: [bootstrap]
  package:
    name: "{{ item }}"
    state: present
  loop:
    - acpid
    - alsa-utils
    - ansible
    - arandr
    - bat
    - bind-tools
    - bluez-tools
    - bluez-utils
    - curl
    - dmenu
    - expect
    - firefox
    - fzf
    - git
    - gnupg
    - inetutils
    - inotify-tools
    - mtr
    - nano
    - neovim
    - openbsd-netcat
    - openssh
    - pass
    - pavucontrol
    - pulseaudio
    - pulseaudio-alsa
    - pv
    - python-pip
    - ripgrep
    - rofi
    - socat
    - tcpdump
    - terminator
    - tmux
    - tree
    - vi
    - vlc
    - wget
    - whois
    - xclip
    - xorg
    - xorg-drivers
    - xscreensaver
    - unzip

- name: install extra packages
  become: yes
  become_user: root
  tags: [bootstrap]
  package:
    name: "{{ item }}"
    state: present
  loop:
    - calibre
    - cowsay
    - dmenu
    - feh
    - figlet
    - flameshot
    - jq
    - keynav
    - helm
    - hexyl
    # - hunspell-pt-br
    - p7zip
    # - pakku
    - parallel
    - rustup
    - ttf-roboto
    - ttf-roboto-mono

- name: install aur packages
  include_tasks: aura.yml
  tags: [bootstrap]
  vars:
    package: "{{ item }}"
  loop:
    - adwaita-qt5
    # - bluez-firmware
    - brave-bin
    - duc
    - otf-symbola
    - pass-git-helper
    - powerline-fonts-git
    - qt5ct

- import_tasks: vlc.yml
  tags: [vlc]

- import_tasks: acpid.yml
  tags: [acpid]

...
