---

- name: packages
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bluez
    - bluez-libs
    - bluez-utils
    - bluez-tools
    - pulseaudio-bluetooth

- name: auto power on
  become: yes
  become_user: root
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^#AutoEnable'
    line: "AutoEnable=true"

- name: mouse config
  become: yes
  become_user: root
  copy:
    src: bt-mouse.conf
    dest: /etc/X11/xorg.conf.d/80-bt-mouse.conf
    mode: 0644
    owner: root

...
