---

# https://f-santos.gitlab.io/2020-04-24-mu4e.html

- name: install packages
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  loop:
    - isync

- name: install aur packages
  include_tasks: aura.yml
  vars:
    package: "{{ item }}"
  loop:
    - mu

- name: ensure mbsyncrc dir
  file:
    dest: "{{ home }}/.config/mbsync/"
    mode: 0700
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    state: directory

- name: ensure mbsync dir
  file:
    dest: "{{ home }}/email/mbsyncmail/"
    mode: 0700
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    state: directory

- name: mbsyncrc file
  copy:
    src: mbsyncrc
    dest: "{{ home }}/.config/mbsync/.mbsyncrc"
    owner: "{{ my_user }}"
    mode: 0600

- name: sync account
  command: 'mbsync --config "{{ home }}/.config/mbsync/.mbsyncrc" appleaccount'

- name: mu init
  command: 'mu init --maildir="{{ home }}"/email/mbsyncmail/'

- name: mu index
  command: 'mu index'

...
