---

- import_tasks: bitlbee.yml
  tags: [bitlbee]

- import_tasks: ssh.yml
  tags: [ssh]

- import_tasks: ntp.yml
  tags: [ntpd]

- import_tasks: swap.yml
  become: true
  become_user: root
  tags: [swap]

- import_tasks: xscreensaver.yml
  tags: [xscreensaver]

- import_tasks: bluetooth.yml
  tags: [bluetooth]

- import_tasks: netdata.yml
  become: true
  become_user: root
  tags: [netdata]

- import_tasks: nix.yml
  tags: [nix]

- import_tasks: mail.yml
  tags: [mail]

...
