---

- name: install netdata
  package:
    name: netdata
    state: present

- name: configure netdata
  copy:
    src: netdata.conf
    dest: /etc/netdata/netdata.conf
    owner: root
    mode: 0644
  notify: restart netdata

- name: netdata service
  systemd:
    name: netdata
    state: started
    enabled: true

...
