---

- name: install ntpd
  become: true
  become_user: root
  package:
    name: ntp
    state: present

- name: ntp.conf
  become: true
  become_user: root
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    mode: 0644
    owner: root

- name: start/enable ntpd
  become: true
  become_user: root
  systemd:
    name: ntpd
    state: started
    enabled: true

...
