---

- name: install emacs
  become: yes
  become_user: root
  package:
    name: emacs-nativecomp
    state: present

- name: clone .emacs.d
  ansible.builtin.git:
    repo: git@github.com:thalesmg/my-emacs-config.git
    dest: "{{ home }}/.emacs.d/"

...
