---

- name: Download and install
  become: yes
  become_user: root
  command: curl -sSL https://get.haskellstack.org/ | sh

- name: Update Stack
  command: stack update

- name: Install GHCI Gloabally
  become: yes
  become_user: root
  command: stack setup
