---

- name: download and install
  become: yes
  become_user: root
  shell: curl -sSL https://get.haskellstack.org/ | sh

- name: update stack
  command: stack update

- name: install ghci gloabally
  become: yes
  become_user: root
  command: stack setup

...
