---

# - import_tasks: stack.yml
#   tags: [stack]

- import_tasks: ghcup.yml
  tags: [ghcup]

- import_tasks: nix.yml
  tags: [nix]

# - import_tasks: bedel-bot.yml
#   tags: [bedel-bot]

# - import_tasks: lsp.yml
#   tags: [haskell-lsp]

...
