---

- name: Check that Stack is installed
  stat:
    path: "{{ item }}"
  with_items:
    - "/usr/local/bin/stack"
    - "/usr/bin/stack"
  register: stack
  changed_when: (stack.stat.exists == False) and not stack

- include: installation.yml
  when: False and stack.changed
