---

- name: check whether stack is installed
  stat:
    path: "{{ item }}"
  loop:
    - /usr/local/bin/stack
    - /usr/bin/stack
  register: stack
  changed_when: not stack or not stack.stat.exists

- include: installation.yml
  when: stack.changed

- name: upgrade stack
  shell: stack update && stack upgrade

...
