---

- name: install docker and friends
  become: yes
  become_user: root
  package:
    name:
      - docker
      - docker-compose
    state: present

- name: add local user to docker group
  become: yes
  become_user: root
  user:
    name: "{{ my_user }}"
    append: yes
    groups: docker

...
