---

- name: install docker and friends
  become: yes
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-compose

- name: add local user to docker group
  become: yes
  become_user: root
  user:
    name: "{{ my_user }}"
    append: yes
    groups: docker
