---

- name: install cl-launch
  include_tasks: aura.yml
  vars:
    package: cl-launch

- name: create script folder
  file:
    dest: "{{ home }}/common-lisp/"
    state: directory
    mode: 0700

- name: papiros
  set_fact:
    papiros:
      - main
      - vlc
      - misc
      - dbus

- name: copy asd system
  template:
    src: meus-papiros.asd
    dest: "{{ home }}/common-lisp/meus-papiros.asd"
    mode: 0700
  notify:
    - deploy cl scripts

- name: copy Makefile
  template:
    src: Makefile
    dest: "{{ home }}/common-lisp/Makefile"
    mode: 0700

- name: copy papiros
  template:
    src: "{{ item }}.lisp"
    dest: "{{ home }}/common-lisp/{{ item }}.lisp"
    mode: 0700
  loop: "{{ papiros }}"
  notify:
    - deploy cl scripts

...
