---

- name: xmonad folder
  file:
    dest: "{{ home }}/.xmonad"
    state: directory
    mode: 0744

- name: config files
  template:
    src: "{{ item.file }}"
    dest: "{{ home }}/{{ item.path }}"
    mode: 0744
  notify: recompile xmonad
  loop:
    - file: xmonad.hs
      path: .xmonad/xmonad.hs
    - file: xmobarrc
      path: .xmobarrc
  loop_control:
    label: "{{ item.path }}"

- name: hooks folder
  become: yes
  become_user: root
  file:
    dest: /etc/pacman.d/hooks
    state: directory
    owner: root
    mode: 0755

- name: pacman hook
  become: yes
  become_user: root
  template:
    src: xmonad.hook
    dest: /etc/pacman.d/hooks/xmonad.hook
    owner: root
    mode: 0755

...
